### PR TITLE
Add rating bar, favorite button, prices and social media buttons on auth page

### PR DESCRIPTION
**Pull request by Azmaa22**
…uth page

### CODE REVIEW

**Comment by Azmaa22** [comment]
@TarekAlabd  I try do all things you told me , I will wait your review and comments

**Comment by TarekAlabd** [comment]
@Azmaa22 
Great work, Asmaa
Can you add me as a Reviewer in the pull request?

**Comment by Azmaa22** [comment]
> @Azmaa22
> Great work, Asmaa
> Can you add me as a Reviewer in the pull request?

**Comment by Azmaa22** [comment]
> @Azmaa22
> Great work, Asmaa
> Can you add me as a Reviewer in the pull request?

How can I add you as Reviewer? I searched but I arrived to anything -_-

**Comment by TarekAlabd** [comment]
> > @Azmaa22
> > Great work, Asmaa
> > Can you add me as a Reviewer in the pull request?
> 
> How can I add you as Reviewer? I searched but I arrived to anything -_-

If you open this page of a pull request from your laptop, you will find something like a navbar on the right.
It contains some components like Reviewers, Assignees, Labels, and so on.
It's an important thing to fill these data, click on reviewers and add me as a reviewer, and add you as an assignee, and so on.

**Comment by Azmaa22** [comment]
> > > @Azmaa22
> > > Great work, Asmaa
> > > Can you add me as a Reviewer in the pull request?
> > 
> > 
> > How can I add you as Reviewer? I searched but I arrived to anything -_-
> 
> If you open this page of a pull request from your laptop, you will find something like a navbar on the right. It contains some components like Reviewers, Assignees, Labels, and so on. It's an important thing to fill these data, click on reviewers and add me as a reviewer, and add you as an assignee, and so on.



> > > @Azmaa22
> > > Great work, Asmaa
> > > Can you add me as a Reviewer in the pull request?
> > 
> > 
> > How can I add you as Reviewer? I searched but I arrived to anything -_-
> 
> If you open this page of a pull request from your laptop, you will find something like a navbar on the right. It contains some components like Reviewers, Assignees, Labels, and so on. It's an important thing to fill these data, click on reviewers and add me as a reviewer, and add you as an assignee, and so on.

https://drive.google.com/file/d/1j1prAApkq9xwtHToLl2EqgLJnFW3qx8f/view?usp=sharing.     I can't access any one of them

**Comment by Azmaa22** [comment]
> > > > @Azmaa22
> > > > Great work, Asmaa
> > > > Can you add me as a Reviewer in the pull request?
> > > 
> > > 
> > > How can I add you as Reviewer? I searched but I arrived to anything -_-
> > 
> > 
> > If you open this page of a pull request from your laptop, you will find something like a navbar on the right. It contains some components like Reviewers, Assignees, Labels, and so on. It's an important thing to fill these data, click on reviewers and add me as a reviewer, and add you as an assignee, and so on.
> 
> > > > @Azmaa22
> > > > Great work, Asmaa
> > > > Can you add me as a Reviewer in the pull request?
> > > 
> > > 
> > > How can I add you as Reviewer? I searched but I arrived to anything -_-
> > 
> > 
> > If you open this page of a pull request from your laptop, you will find something like a navbar on the right. It contains some components like Reviewers, Assignees, Labels, and so on. It's an important thing to fill these data, click on reviewers and add me as a reviewer, and add you as an assignee, and so on.
> 
> https://drive.google.com/file/d/1j1prAApkq9xwtHToLl2EqgLJnFW3qx8f/view?usp=sharing. I can't access any one of them

Do I create a pull request other than this or is there a solution to this problem? @TarekAlabd

**Review by TarekAlabd — APPROVED** [review]
Great work!

**Pull request merged**
